<a href="https://colab.research.google.com/github/olkanth/MSCS_634_Lab_4/blob/main/MSCS_634_Lab_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Laxmi Kanth Oruganti
### MSCS-634 : Advanced Big Data and Data Mining
### Lab 4: Regression Analysis with Regularization Techniques

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Step 1: Data Preparation

In [ ]:
# Load the Diabetes dataset from sklearn.datasets.
from sklearn.datasets import load_diabetes
diabetes = load_diabetes()
# Print the shape of the data and target.
print(diabetes.data.shape)
print(diabetes.target.shape)
# diabetes.target
df = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
df['target'] = diabetes.target
df.head(10)

(442, 10)
(442,)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0
5,-0.092695,-0.044642,-0.040696,-0.019442,-0.068991,-0.079288,0.041277,-0.076395,-0.041176,-0.096346,97.0
6,-0.045472,0.050680,-0.047163,-0.015999,-0.040096,-0.024800,0.000779,-0.039493,-0.062917,-0.038357,138.0
7,0.063504,0.050680,-0.001895,0.066629,0.090620,0.108914,0.022869,0.017703,-0.035816,0.003064,63.0
8,0.041708,0.050680,0.061696,-0.040099,-0.013953,0.006202,-0.028674,-0.002592,-0.014960,0.011349,110.0
9,-0.070900,-0.044642,0.039062,-0.033213,-0.012577,-0.034508,-0.024993,-0.002592,0.067737,-0.013504,310.0

In [ ]:
# Explore the dataset’s features, target values, and data distribution
df.describe()

# Perform any necessary data cleaning steps (e.g., handling missing values).
df.isnull().sum()
# df.isna().sum()

age       0
sex       0
bmi       0
bp        0
s1        0
s2        0
s3        0
s4        0
s5        0
s6        0
target    0
dtype: int64

## Step 2: Linear Regression

In [ ]:
# Implement a Simple Linear Regression model using one feature as the independent variable and the target variable as the dependent variable
# Split the data into training and testing sets.

# Visualize the model's predictions against the actual data.

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X = df[['bmi']]
y = df[['target']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

model.coef_, model.intercept_

(array([[998.57768914]]), array([152.00335421]))

In [ ]:
# Train the model and evaluate its performance using MAE, MSE, RMSE, and R²
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R²:", r2)

MAE: 52.259976445345536
MSE: 4061.8259284949268
RMSE: 63.73245584860925
R²: 0.23335039815872138